name: satu_ayat
description: A new Flutter project for show 1 random ayat Al-Quran

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.3
  flutter_local_notifications: 14.1.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  audioplayers: ^3.0.1
  screenshot: ^2.1.0
  esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/